### ISSUE TITLE
Virtual Fido device demo not working with Yubikey test page (or any other passkey demo page)

### ISSUE THREAD

**Issue by sundayScoop** [bulwarkid/virtual-fido#24] opened 2023-07-18 05:40 UTC
## Installation steps:
1. `git clone https://github.com/bulwarkid/virtual-fido.git`
2. `cd ./cmd/demo/usbip/bin`
3. `./usbip.exe install -w`
4. `cd {where we cloned virtual-fido}`
5. `go run ./cmd/demo start`

## List of errors I've encountered at different sites:
![image](https://github.com/bulwarkid/virtual-fido/assets/87186823/c1df1ebf-2ea3-4bb2-8fa8-79d69eade175)
![image](https://github.com/bulwarkid/virtual-fido/assets/87186823/271ff149-8286-4ca0-8481-40d901eda3c5)

## Log output of virtual-fido application:
```
PS C:\Users\admin\source\repos\Virtual-Authenticator\virtual-fido> go run ./cmd/demo start
[LOG] Log Level Set: 2
succesfully attached to port 0
[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: CTAPHID_BROADCAST_CHANNEL, Command: ctapHIDCommandInit, PayloadLength: 8 } []byte{0x58, 0x5d, 0xa5, 0x7f, 0x7e, 0x75, 0xa1, 0xda}

[CTAPHID] CTAPHID INIT RESPONSE: ctap_hid.initReponse{Nonce:[8]uint8{0x58, 0x5d, 0xa5, 0x7f, 0x7e, 0x75, 0xa1, 0xda}, NewChannelID:0x1, ProtocolVersion:0x2, DeviceVersionMajor:0x0, DeviceVersionMinor:0x0, DeviceVersionBuild:0x1, CapabilitiesFlags:0x4}

[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: 0x1, Command: ctapHIDCommandCBOR, PayloadLength: 1 } []byte{0x4}

[CTAP] CTAP COMMAND: ctapCommandGetInfo

[CTAP] GET_INFO RESPONSE: ctap.getInfoResponse{Versions:[]string{"FIDO_2_0", "U2F_V2"}, AAGUID:[16]uint8{0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5}, Options:ctap.getInfoOptions{IsPlatform:false, CanResidentKey:true, HasClientPIN:(*bool)(nil), CanUserPresence:true}, PINUVAuthProtocols:[]uint32(nil)}

[CTAPHID] CTAPHID CBOR RESPONSE: []byte{0x0, 0xa3, 0x1, 0x82, 0x68, 0x46, 0x49, 0x44, 0x4f, 0x5f, 0x32, 0x5f, 0x30, 0x66, 0x55, 0x32, 0x46, 0x5f, 0x56, 0x32, 0x3, 0x50, 0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5, 0x4, 0xa3, 0x62, 0x72, 0x6b, 0xf5, 0x62, 0x75, 0x70, 0xf5, 0x64, 0x70, 0x6c, 0x61, 0x74, 0xf4}

[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: CTAPHID_BROADCAST_CHANNEL, Command: ctapHIDCommandInit, PayloadLength: 8 } []byte{0x75, 0x15, 0x92, 0xd9, 0x17, 0x2, 0xe8, 0x1d}

[CTAPHID] CTAPHID INIT RESPONSE: ctap_hid.initReponse{Nonce:[8]uint8{0x75, 0x15, 0x92, 0xd9, 0x17, 0x2, 0xe8, 0x1d}, NewChannelID:0x2, ProtocolVersion:0x2, DeviceVersionMajor:0x0, DeviceVersionMinor:0x0, DeviceVersionBuild:0x1, CapabilitiesFlags:0x4}

[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: 0x2, Command: ctapHIDCommandCBOR, PayloadLength: 1 } []byte{0x4}

[CTAP] CTAP COMMAND: ctapCommandGetInfo

[CTAP] GET_INFO RESPONSE: ctap.getInfoResponse{Versions:[]string{"FIDO_2_0", "U2F_V2"}, AAGUID:[16]uint8{0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5}, Options:ctap.getInfoOptions{IsPlatform:false, CanResidentKey:true, HasClientPIN:(*bool)(nil), CanUserPresence:true}, PINUVAuthProtocols:[]uint32(nil)}

[CTAPHID] CTAPHID CBOR RESPONSE: []byte{0x0, 0xa3, 0x1, 0x82, 0x68, 0x46, 0x49, 0x44, 0x4f, 0x5f, 0x32, 0x5f, 0x30, 0x66, 0x55, 0x32, 0x46, 0x5f, 0x56, 0x32, 0x3, 0x50, 0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5, 0x4, 0xa3, 0x62, 0x72, 0x6b, 0xf5, 0x62, 0x75, 0x70, 0xf5, 0x64, 0x70, 0x6c, 0x61, 0x74, 0xf4}
```

**Comment by cmdli** [comment] 2023-07-18 23:09
Hmm, I just tried it on Windows 10/Firefox and I'm having trouble reproducing. It seems to work normally for me. Looking that the logs, I don't see any difference between the data that my version is returning and yours. What browser and OS version are you using? Sometimes different browsers and OS's have different behavior around authenticators.

**Comment by sundayScoop** [comment] 2023-07-19 04:57
Using Brave (which is Chromium), on Windows 10. I downloaded the BulwarkId executable (windows) and it worked. I just couldn't get the master branch on virtual-fido working. Maybe there's a stable branch/version?

**Comment by cmdli** [comment] 2023-07-19 20:58
Ok, I'm able to repro the issue with passkeys.io, but it does seem to work with https://demo.yubico.com/webauthn-technical/registration. What is the website from the first screenshot? It looks like that might be a different error. I appreciate trying out Bulwark Passkey and knowing that that works; it helps me narrow it down. That uses a slightly older version of VirtualFIDO (though not that much older), so maybe something changed recently.

**Comment by cmdli** [comment] 2023-07-19 21:10
For what it's worth, it looks like https://www.passkeys.io doesn't work with my physical Yubikey. After taking a look at it a bit further and by lying about the VirtualFIDO capability info, it looks like that website requires the authenticator to do User Verification (i.e. manually verifying the user's identity with something like biometric authentication). VirtualFIDO currently doesn't support that, so I don't think it would work with that specific website, at least for now. Most websites doesn't require verifying the user's identity, so this shouldn't be an issue for them.

**Comment by sundayScoop** [comment] 2023-07-20 01:08
First image is of the Yubico Playground, when I'm trying to add an authentication device:
![image](https://github.com/bulwarkid/virtual-fido/assets/87186823/cdad0466-0477-4c62-b57e-0c75733928d6)

## Logs 
```
PS C:\Users\admin\source\repos\Virtual-Authenticator\virtual-fido> go run .\cmd\demo start
[LOG] Log Level Set: 2
succesfully attached to port 0
[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: CTAPHID_BROADCAST_CHANNEL, Command: ctapHIDCommandInit, PayloadLength: 8 } []byte{0x6e, 0xa2, 0x2d, 0x91, 0x49, 0x35, 0x6d, 0xad}

[CTAPHID] CTAPHID INIT RESPONSE: ctap_hid.initReponse{Nonce:[8]uint8{0x6e, 0xa2, 0x2d, 0x91, 0x49, 0x35, 0x6d, 0xad}, NewChannelID:0x1, ProtocolVersion:0x2, DeviceVersionMajor:0x0, DeviceVersionMinor:0x0, DeviceVersionBuild:0x1, CapabilitiesFlags:0x4}

[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: 0x1, Command: ctapHIDCommandCBOR, PayloadLength: 1 } []byte{0x4}

[CTAP] CTAP COMMAND: ctapCommandGetInfo

[CTAP] GET_INFO RESPONSE: ctap.getInfoResponse{Versions:[]string{"FIDO_2_0", "U2F_V2"}, AAGUID:[16]uint8{0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5}, Options:ctap.getInfoOptions{IsPlatform:false, CanResidentKey:true, HasClientPIN:(*bool)(nil), CanUserPresence:true}, PINUVAuthProtocols:[]uint32(nil)}

[CTAPHID] CTAPHID CBOR RESPONSE: []byte{0x0, 0xa3, 0x1, 0x82, 0x68, 0x46, 0x49, 0x44, 0x4f, 0x5f, 0x32, 0x5f, 0x30, 0x66, 0x55, 0x32, 0x46, 0x5f, 0x56, 0x32, 0x3, 0x50, 0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5, 0x4, 0xa3, 0x62, 0x72, 0x6b, 0xf5, 0x62, 0x75, 0x70, 0xf5, 0x64, 0x70, 0x6c, 0x61, 0x74, 0xf4}

[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: CTAPHID_BROADCAST_CHANNEL, Command: ctapHIDCommandInit, PayloadLength: 8 } []byte{0xde, 0x31, 0x2f, 0xeb, 0xc0, 0xe8, 0x7, 0xdc}

[CTAPHID] CTAPHID INIT RESPONSE: ctap_hid.initReponse{Nonce:[8]uint8{0xde, 0x31, 0x2f, 0xeb, 0xc0, 0xe8, 0x7, 0xdc}, NewChannelID:0x2, ProtocolVersion:0x2, DeviceVersionMajor:0x0, DeviceVersionMinor:0x0, DeviceVersionBuild:0x1, CapabilitiesFlags:0x4}

[CTAPHID] CTAPHID FINALIZED MESSAGE: CTAPHIDMessageHeader{ ChannelID: 0x2, Command: ctapHIDCommandCBOR, PayloadLength: 1 } []byte{0x4}

[CTAP] CTAP COMMAND: ctapCommandGetInfo

[CTAP] GET_INFO RESPONSE: ctap.getInfoResponse{Versions:[]string{"FIDO_2_0", "U2F_V2"}, AAGUID:[16]uint8{0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5}, Options:ctap.getInfoOptions{IsPlatform:false, CanResidentKey:true, HasClientPIN:(*bool)(nil), CanUserPresence:true}, PINUVAuthProtocols:[]uint32(nil)}

[CTAPHID] CTAPHID CBOR RESPONSE: []byte{0x0, 0xa3, 0x1, 0x82, 0x68, 0x46, 0x49, 0x44, 0x4f, 0x5f, 0x32, 0x5f, 0x30, 0x66, 0x55, 0x32, 0x46, 0x5f, 0x56, 0x32, 0x3, 0x50, 0x75, 0x6c, 0x5a, 0xf5, 0xec, 0xa6, 0x1, 0xa3, 0x2f, 0xc6, 0xd3, 0xc, 0xe2, 0xf2, 0x1, 0xc5, 0x4, 0xa3, 0x62, 0x72, 0x6b, 0xf5, 0x62, 0x75, 0x70, 0xf5, 0x64, 0x70, 0x6c, 0x61, 0x74, 0xf4}```

**Comment by cmdli** [comment] 2023-07-24 23:13
Ok, I investigated the Yubikey Playground, and it looks like it requires a form of user verification. Thankfully, unlike passkeys.io, it does accept client PIN verification, though that was recently disabled by default in VirtualFIDO since it breaks certain UI flows for certain configurations (e.g. PopOS+Firefox). To make this work on the platforms that support client PIN's, I added some commands to allows users to enable them from the demo CLI (in https://github.com/bulwarkid/virtual-fido/commit/c0256885902878809ea97dbe488d6937d75b5bc5).

I tried this on the Yubikey Playground and it seems to have fixed the issue. Please try it out and let me know if it works on your end. In the meantime, I'm going to preemptively close this and you can reopen it if there is still an issue.

**Closed by cmdli** 2023-07-24 23:13 UTC
